CREATE TABLE IF NOT EXISTS PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    CURR VARCHAR(3) NOT NULL
);

-- Índice para acelerar búsquedas por producto, marca y rango de fechas
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_BRAND_DATE_PRIORITY
    ON PRICES (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE, PRIORITY);